### PR TITLE
Updated readme with example of code usage

### PR DESCRIPTION
**Pull request by kirlat**
Added some usage examples for #7. Please let me know if you think it's enough. Would appreciate any wording suggestions and improvements. Thanks!

### CODE REVIEW

**Review by balmas — CHANGES_REQUESTED** [review]
I think this is a great start! I committed some edits to the text mainly for grammatical clarity  and some addition of headers, etc. - it was easier to just make the changes than describe them.

I do think we still need a few things:
1.  an overview of the point of the messaging service and its architecture (I left an empty section for that) 
2. A description of how the WindowIFrameDestination is expected to be used
3. A few example scenarios of other types of Destinations one might envision creating

Could you take a stab at those?

**Comment by kirlat** [comment]
I think those are important topics to cover, I will work on them

**Comment by kirlat** [comment]
@balmas, I've added an architectural diagram and appended missing data to the readme. Please let me know if any further corrections or additions are required. Thanks!

**Review by balmas — APPROVED** [review]
looks great. thank you!

**Pull request merged**
